# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://admin:bzd9ujtNC01i0Y59@cluster0.r36gfft.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
spring.data.mongodb.database=Cluster0

# Server Configuration
server.port=8080

# Logging Level
logging.level.org.springframework=INFO
logging.level.com.mongodb=DEBUG

# Swagger UI Config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# apis url
eventos.service.url=http://localhost:8080/eventos