spring.application.name=espacios-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://root:rootpassword@mongodb:27017/espacios_db?authSource=admin
spring.data.mongodb.database=espacios_db

# RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Swagger UI Config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# Eventos Service - Usa el nombre del servicio en docker
eventos.service.url=http://eventos-service:8080/api/eventos

# Server Configuration
server.port=8081