spring.application.name=reservas-service

# MongoDB Configuration
spring.data.mongodb.uri=mongodb://root:rootpassword@mongodb:27017/reservas_db?authSource=admin
spring.data.mongodb.database=reservas_db

# Server Configuration
server.port=8082

# Logging Level
logging.level.org.springframework=INFO
logging.level.com.mongodb=DEBUG

# Swagger UI Config
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# apis url - Usa el nombre del servicio en docker
eventos.service.url=http://eventos-service:8080/api/eventos

# RabbitMQ Configuration
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Exchange and Queue names
event.exchange=reservas-exchange
event.queue.reserva-creada=reserva-creada-queue
event.queue.reserva-cancelada=reserva-cancelada-queue
event.routing-key.reserva-creada=reserva.creada
event.routing-key.reserva-cancelada=reserva.cancelada