# Configuración del servidor
server.port=8080
server.host=0.0.0.0

# Configuración de OpenAPI
mp.openapi.extensions.enabled=true

# RabbitMQ Configuration
rabbitmq.host=rabbitmq
rabbitmq.port=5672
rabbitmq.username=guest
rabbitmq.password=guest

# Retrofit Configuration
retrofit.eventos-service.url=http://eventos-service:8080/api/eventos